language: python
python:
  - 3.8


before_install:
  - python --version
  - pip install -U pip
install:
  - cd src
  - pip install ".[test]" . # install package + test dependencies
  - pip install "." .       # install package + test dependencies
script: pytest --cov=src/sticky_pi_api         # run tests
after_success:
  - codecov                 # submit coverage

