language: python
python:
  - 3.8
before_script: cd src

before_install:
  - python --version
  - pip install -U pip
install:
  - pip install ".[test]" . # install package + test dependencies
  - pip install ".[docs]" . # install package + test dependencies
  - pip install "." . # install package + test dependencies
script: pytest      # run tests
after_success:
  - codecov # submit coverage

