version: '3'

services:
  api:
    build: ./api
    container_name: api
    restart: always
    expose:
      - 8080
      
  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"
  
# we also need to add db, rshiny, s3 and probably localstack  to services