version: '3'


services:

  spi_db:
    container_name: spi_db
    image: mariadb
    restart: always
    env_file:
      - .env
      - .secret.env
      - ${EXTRA_ENV}
  spi_api:
    build: ./api
    container_name: spi_api
    restart: always
    depends_on:
      - spi_db
      - spi_nginx
    expose:
      - 8080
#    ports:
#      - "5000:5000"

    env_file:
      - .env
      - .secret.env
      - ${EXTRA_ENV}
  spi_api_tests:
    build: ./api
    container_name: spi_api_tests
    command: python -m unittest api_tests.py
    depends_on:
      - spi_api
      - spi_db
      - spi_nginx
    env_file:
      - .env
      - .secret.env
      - ${EXTRA_ENV}

  spi_nginx:
    build: ./nginx
    container_name: spi_nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
  #https://medium.com/@pentacent/nginx-and-lets-encrypt-with-docker-in-less-than-5-minutes-b4b8a60d3a71
  certbot:
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot