version: '3'

services:
  spi_db:
    container_name: spi_db
    restart: always
    image: mariadb
    env_file:
      - .env
      - .secret.env

  spi_api:
    container_name: spi_api
    restart: always
    build:
      context: ./api
      args:
        API_PORT: ${API_PORT}
    depends_on:
      - spi_db
    expose:
      - ${API_PORT}
    env_file:
      - .env
      - .secret.env

  spi_webapp:
    container_name: spi_webapp
    restart: always
    build:
      context: ./webapp
    ports:
      - ${WEBAPP_PORT}:80
    env_file:
      - .env
      - .secret.env
    depends_on:
      - spi_api

  spi_uid:
    container_name: spi_uid
    restart: always
    build:
      context: ./ml
    command: 'python uid.py -v predict'
    environment:
      - BUNDLE_ROOT_DIR=/opt/ml_bundle_dir/ # - ${LOCAL_VOLUME_ROOT}/client/ml/
      - LOCAL_CLIENT_DIR=/opt/api_api_client/ #${LOCAL_VOLUME_ROOT}/client/

    depends_on:
      - spi_api
    env_file:
      - .env
      - .secret.env

  spi_nginx:
    container_name: spi_nginx
    restart: always
    build:
      context: ./nginx
      args:
        API_PORT: ${API_PORT}
        WEBAPP_PORT: ${WEBAPP_PORT}
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    ports:
      - "80:80"
    env_file:
      - .env
      - .secret.env
    depends_on:
      - spi_api
      - spi_webapp

  spi_localstack:
    container_name: spi_localstack
    image: localstack/localstack
    ports:
      - '4566:4566'
      - '8055:8080'
    environment:
      - SERVICES=s3
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
    env_file:
      # TODO add relevant configurations to .env file
      - .env
    volumes:
      - '${TMPDIR:-/tmp/localstack}:/tmp'
      - '/var/run/docker.sock:/var/run/docker.sock'
