version: '3'

services:
  spi_db:
    volumes:
      - ${LOCAL_VOLUME_ROOT}/mysql:/var/lib/mysql
#  spi_uid:
#      env_file:
#        - .prod.env

  spi_nginx:
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ${LOCAL_VOLUME_ROOT}/data/certbot/conf:/etc/letsencrypt
      - ${LOCAL_VOLUME_ROOT}/data/certbot/www:/var/www/certbot

  #https://medium.com/@pentacent/nginx-and-lets-encrypt-with-docker-in-less-than-5-minutes-b4b8a60d3a71
  spi_certbot:
    container_name: spi_certbot
    image: certbot/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    volumes:
      - ${LOCAL_VOLUME_ROOT}/data/certbot/conf:/etc/letsencrypt
      - ${LOCAL_VOLUME_ROOT}/data/certbot/www:/var/www/certbot
