version: '3'

services:
  spi_db:
    container_name: spi_db
    restart: always
    image: mariadb
    env_file:
      - .env
      - .secret.env

  spi_api:
    container_name: spi_api
    restart: always
    build:
      context: ./api
      args:
        API_PORT: ${API_PORT}
    depends_on:
      - spi_db
    expose:
      - ${API_PORT}
    env_file:
      - .env
      - .secret.env

  spi_webapp:
    container_name: spi_webapp
    restart: always
    build:
      context: ./webapp
    ports:
      - ${WEBAPP_PORT}:80
    env_file:
      - .env
      - .secret.env
    depends_on:
      - spi_api

  spi_uid:
    container_name: spi_uid
      restart: always
    depends_on:
      - spi_api

  spi_nginx:
    container_name: spi_nginx
    restart: always
    build:
      context: ./nginx
      args:
        API_PORT: ${API_PORT}
        WEBAPP_PORT: ${WEBAPP_PORT}
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    ports:
      - "80:80"
    env_file:
      - .env
      - .secret.env
    depends_on:
      - spi_api
      - spi_webapp

